### ISSUE TITLE
verify requires api_id and api_key

### ISSUE THREAD

**Issue by wndxlori** [titanous/yubikey#13]
This is more like a question, than a problem report.  I find myself in the position of fixing the yubikey_database_authenticatable gem (for use with Devise), in order to work with the 1.3 release.  And I have got it working, but I'd like to get it working _right_.

The problem is that yubikey_database_authenticatable, when calling the OTP::Verify.new, needs to send the api_id and api_key parameters.  Now, I started to fix this problem by adding a configuration module that allows me to set defaults for those two values in an initializer for my Rails app.  But this gem feels like the wrong place to add this configuration, since yubikey_database_authenticatable doesn't need to do anything except pass those values thru.  Yubikey gem is the one that _requires_ these two parameters.

Would you accept a pull request to add a configuration module that sets defaults for api_id and api_key in the yubikey gem?

**Comment by ukd1** [comment]
As long as it's well tested and it doesn't break existing use in 1.3 then I'm fine with this.

**Comment by ukd1** [comment]
Closed as it's being dealt with by #14
