### ISSUE TITLE
Chain File is missing in gemspec. Intentional?

### ISSUE THREAD

**Issue by halfbyte** [titanous/yubikey#17]
I've just tried out this gem and the otp validation example from the readme fails because the certificate file is not contained in the gem. As it is on github, I must assume that this is an error?

I would do a pull request, but wanted to check first if I missed something.

I've fixed this so far for me by downloading the pem and using args[:certificate_chain]

**Comment by titanous** [comment]
Looks like a bug, a PR would be fantastic.
